# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "raha-terraform-state-v1"
    dynamodb_table = "my-lock-table"
    encrypt        = true
    key            = "terraform.tfstate"
    region         = "us-west-2"
  }
}
